name: test
permissions:
  contents: read

on:
  push:
    branches: [ "main", "ghtest" ]

jobs:

  # https://docs.github.com/en/actions/tutorials/create-an-example-workflow
  test-os:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: bash ./bin/run-lint.sh
    - run: bash ./bin/run-test.sh
    - run: npm run e2e

  # https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/run-jobs-in-a-container
  test-container:
    runs-on: ubuntu-latest
    container: fedora:latest
    timeout-minutes: 10

    steps:
    - name: Install git
      # Needs to be done before the actions/checkout step, otherwise it will fall back to fetching the code over http:
      # "The repository will be downloaded using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH"
      run: dnf install -y git
    - name: Check out code
      uses: actions/checkout@v4
    - name: Avoid dubious ownership error
      run: chown -R root:root .
    - name: Install dev dependencies
      run: bash ./bin/ci-install-dependencies.sh
    - run: npm ci
    - run: bash ./bin/run-lint.sh
    - run: bash ./bin/run-test.sh
    - run: npm run e2e
